# Generated by Django 5.1.6 on 2025-02-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uuid',
        ),
    ]
